# Generated by Django 2.0.3 on 2020-06-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram',
            name='estado',
            field=models.CharField(choices=[('Publicado', 'Publicado'), ('Borrador', 'Borrador')], default='Publicado', max_length=12),
        ),
    ]
