# Generated by Django 2.0.3 on 2020-07-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instaapp', '0002_auto_20200622_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagram',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Publicado', 'Publicado')], default='Publicado', max_length=12),
        ),
    ]
