# Generated by Django 2.0.3 on 2020-07-29 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galeriaapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='estado',
            field=models.CharField(choices=[('Borrador', 'Borrador'), ('Publicado', 'Publicado')], default='Publicado', max_length=12),
        ),
    ]
